# /server/Dockerfile

FROM node:16-slim

WORKDIR /app

# Install Python and other build tools
RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install --only=production  # Install only production dependencies

# Copy the rest of the application code
COPY . .

# Rebuild native modules
RUN npm rebuild bcrypt --build-from-source

# Set the NODE_ENV environment variable
ENV NODE_ENV=production

EXPOSE 3000

# Use npm start instead of calling node directly
CMD ["npm", "start"]
